language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: react-performance-test
  api_key:
    secure: LmIY8JEQE4DMEw8Vat5q5h/1pxmpU8nfbR5slNI2lLWoqLbEN63BnSOHS8TvhWPkn8cOH9oIqX7RqbnySLGw0byoTgTXvenGizoNaOeJKGstsE+Hl8Hm7+YTIJmfsa3cf67DpfVoNZal3p98K28gbIvI5+5LcllTT1KPhsCZf+9XgPlccfWQCBtTUltItBTEvQ4cK+XgWpFxCX1rVtRNgMyeXNbIGtYiyVU8lFBXRSuW0WEkdh5LyeV8auJ9haEB9TfIe9pALqOaO+dcXEIfQ4MQ+sxm3f7YuJlVss2py1DT2w2VQRC5DhLVK561uDxkd3Yc5/6iB9B7MRjfUOx4xabd/cQ1xYtF9wZhwOk87SbokUKrh5w4keDUswlKXHZvOR4QQA2JhhJw1hQZQbb9GGTO8WG8OO7L0zaOo90htoUFgnB09HmAXkJhhbuEwIbsTqwu3qVTzghSsc+seUOSp9uNs164zCKcilP3tc0oGATnpcvnAMltEeOG+cuDouQIT7DLDpD9JC876TvglK8+XOlFChPVBKXF8HX7X61isPX9ClfzK1/vpxLzELhS3rillUWfwmyQxBB98TbDPctcvSfFZQPWURJda12id+gOk2TOGVMPee3RJhDW4BafMn4i59htENd9/tsHOidfwSqF9tsinWAWUR4Hc43zhXDNOTI=
  on:
    repo: degreeproject/react-performance-test
    branch: master
