language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: react-performance-test
  api_key:
    secure: ZkD6/70Jq32PJp1QcDYsskWMt9WkYaOVK3LtCl/zNkyVcAylnTO1UJZdzqvoQDM2fykcm61A2xjENtvRX5CPCe8ikTYyr3scOrq+DisacUpvburXoBzi4tOx5rkP4Q1kzvFq2EVxVDCONWSmGgJqFhQj0VMF4+kfqARyA55FVEYr0gQuhpkDHkKTd9yvH8flBy7wzn3EcTvsCSOL2OrDxCW6/7MhtBf5VDGri4fLBw9H0W+16NERUSpvoitsPtz2FgS6d+twXxpZaCRFPYziiKZRKkkirsCf5ZAu8MWV/fv4riGCHZG088GIeUxaNIVyvrts6ZmVqA0ybtFvKvZjSbQQ1bg9y1K/2OOgZeQz2vi15zZfPi/sP+2AKCrdnu/O4lydaV6FK/0BnL38EqVyX+LFPMwXPb4M3q/5DWY1vsvyJeSeh3/LVZZVh0/wB7lnnHLHf1BD9iRJGsH14u/h5mi8Ax64yMOk5yGKgF1HUZW5ACGIAyBinuQFcmhSRIw37Z/Lhw21o+ygisqq2gxRNRtN029qwbTXnyoW+IWMhVSDLc7c0Luk3QO84wldBZ1P0uJ7X8JQztTBP+uNSJJGSEIreIBsMuXnKQ/ta22hLmQUr7GUQwa7FpnB66Te68lmYa0FrCbLZOQL97dflOmbcamqyZelyXkfvXG4un/WRkk=
  on:
    repo: degreeproject/react-performance-test
    branch: master
