language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: react-performance-test
  api_key:
    secure: cXgmblg1PytP7/6324UElXWckj46r3wwgKXZJxXUnOiUpfhJe39EIim/I09sUx26x5wMIq5vFs+28BC6DRhdPFAosrUWE3NVz2VVQ5p23MhqqGeG3VJc1VuCu7IKJEWPQwjyWI2SmjnPzQ8MEf0kH5pmNKuHurONMU7fryVSMtyqc+Wq8ePfp0yQrM+rk8D/UrTgoJNwGxHmKYivNak+i/2dt868agJl2a42+BQ18+eo/1SfAPlTSXW72rpzruhASoDMfmUBgUBmhDuLvngkgw61bA4dlonDm6ODqObixnqXzjFIrI8hOlCRoDfuZADdyAs03TrzBSXwejgQS/kli4GkMWyJreQau9MD/PKnbrpm2Wso01NMfXs1ecikVdWRsSFBxYRntV2jjM8ZL+tZrNBeVCK1LF+EBIYjzsM8LYIhXVanCmbfEm24tuHxRJrznrBYshwi7DAAt86t0evKUwuh05rCeOSVr9RhUIr1cSEBP3n8mchR1kqhslT+ezqmqRP5clwkGRKJ5xI6zsPRiiJfKJU98IFT+pi7dsBFfxZLrhV/26/Sr+r0hsZwisaRK/xt06f5y58rHHTPyksllvq9Wv6V0/dEHVfrK5EGc2mAKFXck6bheLgD3PNLs5kwXnUMzNaypdh5J1KuWKCm5WRaRyBvqa/M+fflRTJxHA8=
  on:
    repo: degreeproject/react-performance-test
    branch: master
