language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: react-performance-test
  api_key:
    secure: Balx1MAdoC6UJC9CP3G3SR0lIM/LU3mOOkmQhP3EbGRO2GYduewpzLsI0AvA8xwvPtap2qC9XeMgODyfZzvihX1h9GeaLHhupwuxxtOPYVRJxUqSsPdDJezJwcJLtMjOXX+vUjCIE25oVyx6rsmufxNJRH06kmhDB5xYnudBOArHm6gWtsBuSkNVT3yVdoOJNI/kCRIvJee7+Oc9rru8DrhAa5uaqEnafTUIUIbIRt8QqojX/OaodS9gxJJCYi8lL18kBehiAScOrSRgO27Sg+tkByeQfRHmSVV6JSaM++hzo3Wi/X8309FMeRE1pouSDg+VM4vLxqu1JlLnk2myu5Am5QXvlX6/YyZudpwkfnbheuM87694r0IU0YcdWRAeGgs1WMjZ/2vl5Z2LvijB/yPo8FbLqOHrVyujE770VLt5tXZiv9azOOYLhPq7TJRYfGTte4PXUEsJC2ABk7CeYl7kC8lMMFqIT7P+kiJLbIVFqUvTVUBhNpQ7QlK08P2xfFFpDtoJZWeMCkLvBkeaT0++U4ur+ZQzClNynGkR950vOqIXq8vAAuw7+QNTBBu3RrXivLqHaGemrjiZNzyhkUaQZrP6+WtZlgZgJkQzvWlQ91A39NPCFERIzlt4TBtOzQGgMXPR/O9dTUh96Cg4UfPZKtHhQJtpnw6iyyu6qhw=
  on:
    repo: degreeproject/react-performance-test
    branch: master
