language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: react-performance-test
  api_key:
    secure: mKr1DXi2aQzcPOjAyapuMPa112op9kkPotk6236rorf1MWDNoORSFfpeZSprfBncPIQq8M9JbPgmZCng0wpECL/ZY7/iEuB0suPwHVHIUymMnPp0h9zTesJQHR6UA9y3eaK+gJd9drAJ4nFM0IFQD3F0p1WWX47hmbFmZZ+k4ShOnEDTxkNbSDxqtgztsV6SZrRBTYAyQhM/bBuql/BTcWso1gENfD5zd0QgiJ4NI1J3MPhjMMEOIaUyIsImln86dVkRteGigTi+i+gW41lrpwgpAt1w3m/I9bzOozfsO1ZkOxkwRwn0zm1A//4V5URMlBK3aimtvVNAJHjThhYpQje1n8R3my2K2nFwbBjFIr2+XtN28G/B0eR1N0LbzL9T7rNWxChEMVZ6VPg6mg+Kd14/ywC6rSn28bhzDMEKiYbPWq4K69sVEnwkD4JLn7sPRiuscKukJnHXf7kMJFbm33sJR+TWsvOrSqXyUzHG5+spKEHsicXrHlfqWRdH9nbdWQ0XQXJjhY2ckguh4uK5Uc/2u2VN4LRzg3ZDhkzp/JbmUeabVX2qzyo05IAPxHF/ZSI5pSt3DsC44ZZfmNQMpoINkFRpj36LRp13ZoJDKk3R0XNwM4chrijwBNqZMiq9IbpMJVtPQAK0MjZXdvb+sXljfE5KkG36048VxRk4D4M=
  on:
    repo: degreeproject/react-performance-test
    branch: master
